"""Update Student model fields

Revision ID: 571b6ddcfce0
Revises: accae2ceadc4
Create Date: 2025-03-11 02:36:21.147867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571b6ddcfce0'
down_revision: Union[str, None] = 'accae2ceadc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'branch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('students', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'fathers_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'interested_in_placement',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('students', 'class_10_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('students', 'class_10_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'class_10_school',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'class_10_board',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'mobile_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'whatsapp_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'home_contact_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'personal_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'permanent_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'home_town',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'home_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'home_state_pin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'tg_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'tg_contact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'tg_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'tg_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'tg_contact',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'tg_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'home_state_pin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'home_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'home_town',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'permanent_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'personal_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'home_contact_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'whatsapp_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'mobile_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'class_10_board',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'class_10_school',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'class_10_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'class_10_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('students', 'interested_in_placement',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('students', 'fathers_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('students', 'branch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
