"""Initial migration

Revision ID: c969ff2abc02
Revises: 
Create Date: 2025-03-10 23:14:02.492027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c969ff2abc02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('registration_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('adhaar_number', sa.String(), nullable=True),
    sa.Column('fathers_name', sa.String(), nullable=False),
    sa.Column('interested_in_placement', sa.Boolean(), nullable=False),
    sa.Column('placement_declaration', sa.Boolean(), nullable=True),
    sa.Column('reason_not_interested', sa.String(), nullable=True),
    sa.Column('class_10_percentage', sa.Float(), nullable=False),
    sa.Column('class_10_year', sa.Integer(), nullable=False),
    sa.Column('class_10_school', sa.String(), nullable=False),
    sa.Column('class_10_board', sa.String(), nullable=False),
    sa.Column('class_12_percentage', sa.Float(), nullable=True),
    sa.Column('class_12_year', sa.Integer(), nullable=True),
    sa.Column('class_12_school', sa.String(), nullable=True),
    sa.Column('class_12_board', sa.String(), nullable=True),
    sa.Column('polytechnic_percentage', sa.Float(), nullable=True),
    sa.Column('polytechnic_year', sa.Integer(), nullable=True),
    sa.Column('polytechnic_institute', sa.String(), nullable=True),
    sa.Column('gpa_1st_sem', sa.Float(), nullable=True),
    sa.Column('gpa_2nd_sem', sa.Float(), nullable=True),
    sa.Column('gpa_3rd_sem', sa.Float(), nullable=True),
    sa.Column('gpa_4th_sem', sa.Float(), nullable=True),
    sa.Column('gpa_5th_sem', sa.Float(), nullable=True),
    sa.Column('gpa_6th_sem', sa.Float(), nullable=True),
    sa.Column('final_cgpa', sa.Float(), nullable=True),
    sa.Column('current_cgpa', sa.Float(), nullable=True),
    sa.Column('active_backlogs', sa.Integer(), nullable=True),
    sa.Column('academic_gap', sa.Integer(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=False),
    sa.Column('whatsapp_no', sa.String(), nullable=False),
    sa.Column('home_contact_no', sa.String(), nullable=False),
    sa.Column('email_smit', sa.String(), nullable=False),
    sa.Column('personal_email', sa.String(), nullable=False),
    sa.Column('permanent_address', sa.String(), nullable=False),
    sa.Column('home_town', sa.String(), nullable=False),
    sa.Column('home_state', sa.String(), nullable=False),
    sa.Column('home_state_pin', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('tg_name', sa.String(), nullable=False),
    sa.Column('tg_contact', sa.String(), nullable=False),
    sa.Column('tg_email', sa.String(), nullable=False),
    sa.Column('updated_cv', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('registration_no'),
    sa.UniqueConstraint('email_smit'),
    sa.UniqueConstraint('personal_email')
    )
    op.create_index(op.f('ix_students_registration_no'), 'students', ['registration_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_registration_no'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
